build_targets:
- commands:
  - apt-get update 
  - apt-get install -y libaio1
  - mvn install
  container:
    image: yourbase/yb_ubuntu:18.04
  name: default

ci:
  builds:
  - build_target: default
    name: default
dependencies:
  build:
  - java:11.0.6
  - maven:3.6.3
